import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { parseInstagramHtmlThread, deriveOffsetMs } from './instagram-html.js';

const HEADER = `<aside class="_aoaa">Generated by duolingo_gao on <time datetime="2026-06-10T03:44Z">Tuesday, June 9, 2026 at 8:44 PM UTC</time>
<div>Contains data you requested from <time datetime="2026-03-10T03:36Z">March 9, 2026 at 8:36 PM</time> to <time datetime="2026-06-10T03:36Z">June 9, 2026 at 8:36 PM</time></div></aside>`;

const block = (sender, bodyInner, when) =>
  `<div class="pam _3-95 _2ph- _a6-g uiBoxWhite noborder"><h2 class="_3-95 _2pim _a6-h _a6-i">${sender}</h2><div class="_3-95 _a6-p"><div><div></div>${bodyInner}<div></div></div></div><div class="_3-94 _a6-o">${when}</div></div>`;

const THREAD_HTML = `<html><head><style>body{}</style></head><body class="_5vb_">
<div class="_li"><div class="_a705"><header><div class="_a70d"><h1>maddie</h1>${HEADER}</div></header>
<main role="main">
${block('maddie', '<div>hey are you free saturday?</div>', 'May 31, 2026 7:55 am')}
${block('Demo User', '<div>Yall got 2 checked off</div>', 'May 31, 2026 7:57 am')}
${block('Demo User', '<div>You sent an attachment.</div>', 'June 1, 2026 9:00 pm')}
</main></div></div></body></html>`;

function writeThread(html) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-html-'));
  fs.writeFileSync(path.join(dir, 'message_1.html'), html);
  return dir;
}

test('deriveOffsetMs reads the header calibration (UTC-7 here)', () => {
  assert.equal(deriveOffsetMs(THREAD_HTML), -7 * 3600 * 1000);
});

test('parseInstagramHtmlThread extracts sender, body, UTC ts, participants', () => {
  const dir = writeThread(THREAD_HTML);
  const t = parseInstagramHtmlThread(dir);
  assert.equal(t.folder, path.basename(dir));
  assert.deepEqual(t.participants.sort(), ['Demo User', 'maddie']);
  assert.equal(t.messages.length, 3);

  const [m1, m2, m3] = t.messages;
  assert.equal(m1.senderName, 'maddie');
  assert.equal(m1.body, 'hey are you free saturday?');
  // 7:55 am local UTC-7 -> 14:55 UTC
  assert.equal(m1.ts, Date.UTC(2026, 4, 31, 14, 55, 0));

  assert.equal(m2.senderName, 'Demo User');
  assert.equal(m2.body, 'Yall got 2 checked off');
  assert.equal(m2.ts, Date.UTC(2026, 4, 31, 14, 57, 0));

  // 9:00 pm local -> next-day 04:00 UTC
  assert.equal(m3.ts, Date.UTC(2026, 5, 2, 4, 0, 0));
  assert.equal(m3.body, 'You sent an attachment.');
  assert.equal(m3.attachmentType, 'image'); // attachment notice flagged
});

test('non-ASCII (emoji) names survive — HTML is real UTF-8, not double-encoded', () => {
  const html = `<html><body><h1>🕺🏻</h1>${HEADER}<main>
${block('🕺🏻', '<div>café ☕ 你好</div>', 'May 31, 2026 7:55 am')}
</main></body></html>`;
  const t = parseInstagramHtmlThread(writeThread(html));
  assert.deepEqual(t.participants, ['Demo User', '🕺🏻']);
  assert.equal(t.messages[0].senderName, '🕺🏻');
  assert.equal(t.messages[0].body, 'café ☕ 你好');
});

test('parseInstagramHtmlThread returns null when no html files', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ig-html-empty-'));
  assert.equal(parseInstagramHtmlThread(dir), null);
});
