#!/usr/bin/env node
// Build the synthetic demo corpus: pipeline/output-demo/raw/messages.duckdb
//
// The demo JSON artifacts (graph, timeline, groups…) are generated by
// generate-demo-data.py. This produces the DuckDB half, using the SAME cast
// and ids so the two agree, which is what lets the database-backed views
// render without anyone's real archive.
//
//   node scripts/generate-demo-db.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DuckDBInstance } from '@duckdb/node-api';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEMO = path.join(ROOT, 'pipeline', 'output-demo');
const OUT = path.join(DEMO, 'raw', 'messages.duckdb');

const graph = JSON.parse(fs.readFileSync(path.join(DEMO, 'graph.json'), 'utf-8'));
const groupsRaw = JSON.parse(fs.readFileSync(path.join(DEMO, 'groups.json'), 'utf-8'));
const GROUPS = Array.isArray(groupsRaw) ? groupsRaw : (groupsRaw.groups || Object.values(groupsRaw));
const SELF_ID = graph.self_id, SELF = 'Demo User';
const PEOPLE = graph.nodes;

// Deterministic PRNG so the corpus is byte-reproducible.
let seed = 20260908;
const rnd = () => (seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
const pick = (a) => a[Math.floor(rnd() * a.length)];
const esc = (s) => s === null || s === undefined ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`;
const arr = (xs) => `[${xs.map(esc).join(',')}]`;

const OPENERS = ['hey', 'you around?', 'ok so', 'quick one', 'morning', 'guess what', 'random but', 'update:'];
const BODIES = [
  'that place on the corner is actually good', 'running about 10 late sorry', 'did you see the thing',
  'i finished it last night, we need to talk about the ending', 'coffee this week?', 'sending you the link now',
  'photos from the weekend', 'thank you, genuinely', 'that was a lot. still processing it',
  'booked the flights', 'how did it go today', 'my brain is soup', 'call when you can',
  'happy birthday!!', 'i think you were right about that', 'the meeting got moved again',
];
const iso = (ms) => new Date(ms).toISOString().replace('T', ' ').slice(0, 19);
const DAY = 86400000;

const messages = [], threadIdentity = [], threads = [], mentions = [], groupMembership = [];
let mid = 0;

// One 1:1 thread per person, message volume scaled down from the graph counts.
for (const p of PEOPLE) {
  const src = p.sources[0];
  const tid = `${src.slice(0, 2)}:${p.name.toLowerCase().replace(/\W+/g, '')}`;
  threads.push({ thread_id: tid, source: src, is_group: false, participants: [SELF, p.name] });
  threadIdentity.push({ thread_id: tid, canonical_id: p.id });
  const t0 = Date.parse(p.first_iso), t1 = Date.parse(p.last_iso);
  const n = Math.max(12, Math.round(p.msg_count / 120));   // ~1% sample, keeps the file small
  for (let i = 0; i < n; i++) {
    const ts = Math.round(t0 + (t1 - t0) * (i / n) + rnd() * DAY * 3);
    const fromMe = rnd() < 0.48;
    const body = rnd() < 0.25 ? pick(OPENERS) : pick(BODIES);
    messages.push({ id: `m${++mid}`, ts, source: src, thread_id: tid, from_me: fromMe,
      sender_name: fromMe ? SELF : p.name, body });
    if (rnd() < 0.05) {
      const other = pick(PEOPLE);
      if (other.id !== p.id) mentions.push({ mentioned_canonical_id: other.id, mentioned_form: other.name.split(' ')[0],
        thread_id: tid, message_id: `m${mid}`, ts, from_me: fromMe });
    }
  }
}

// Group threads, matching the thread_ids already in groups.json.
for (const g of GROUPS) {
  threads.push({ thread_id: g.thread_id, source: g.source, is_group: true, participants: g.participants_raw || [] });
  for (const m of (g.members || [])) {
    const person = PEOPLE.find((p) => p.name === m.sender_name);
    groupMembership.push({ thread_id: g.thread_id, participant_name: m.sender_name, canonical_id: person ? person.id : SELF_ID });
  }
  const t0 = Date.parse(g.first_iso), t1 = Date.parse(g.last_iso);
  const n = Math.max(10, Math.round((g.msg_count || 500) / 150));
  for (let i = 0; i < n; i++) {
    const who = pick(g.participants_raw || [SELF]);
    const ts = Math.round(t0 + (t1 - t0) * (i / n) + rnd() * DAY * 2);
    messages.push({ id: `m${++mid}`, ts, source: g.source, thread_id: g.thread_id,
      from_me: who === SELF, sender_name: who, body: pick(BODIES) });
  }
}
messages.sort((a, b) => a.ts - b.ts);

// Photos in a handful of cities, with faces and events over them.
const CITIES = [
  ['Melbourne', 'Australia', -37.8136, 144.9631], ['Sydney', 'Australia', -33.8688, 151.2093],
  ['Tokyo', 'Japan', 35.6762, 139.6503], ['Lisbon', 'Portugal', 38.7223, -9.1393],
  ['Chicago', 'United States', 41.8781, -87.6298], ['Auckland', 'New Zealand', -36.8485, 174.7633],
];
const photos = [], places = [], photoFaces = [], events = [], eventPhotos = [], faceClusters = [];
for (let i = 0; i < 140; i++) {
  const pid = `ph${i + 1}`;
  const [city, country, lat, lng] = pick(CITIES);
  const ts = Date.parse('2016-01-01') + Math.floor(rnd() * (Date.parse('2026-06-01') - Date.parse('2016-01-01')));
  photos.push({ id: pid, ts, source: 'demo', asset_path: `photos/${pid}.jpg`, width: 1600, height: 1200 });
  places.push({ photo_id: pid, lat: lat + (rnd() - 0.5) * 0.1, lng: lng + (rnd() - 0.5) * 0.1, city, country });
  const who = pick(PEOPLE);
  photoFaces.push({ photo_id: pid, canonical_id: who.id, face_cluster: `c${(PEOPLE.indexOf(who) % 8) + 1}` });
}
PEOPLE.slice(0, 8).forEach((p, i) => faceClusters.push({ cluster_id: i + 1, n_faces: 6 + i, canonical_id: p.id, label: p.name }));
for (let i = 0; i < 24; i++) {
  const eid = `ev${i + 1}`;
  const ph = photos[Math.floor(rnd() * photos.length)];
  const pl = places.find((x) => x.photo_id === ph.id);
  const who = pick(PEOPLE);
  events.push({ event_id: eid, start_ts: ph.ts, end_ts: ph.ts + 4 * 3600000, place_name: pl.city,
    participants: [SELF, who.name], n_photos: 3, n_messages: 8,
    summary: `${pick(['dinner', 'a walk', 'the market', 'a gig', 'a long lunch', 'the beach'])} in ${pl.city} with ${who.name}`,
    source: 'demo', lat: pl.lat, lng: pl.lng });
  eventPhotos.push({ event_id: eid, photo_id: ph.id });
}

const calls = PEOPLE.slice(0, 9).map((p, i) => ({
  call_id: `call${i + 1}`, ts: Date.parse(p.last_iso) - i * DAY * 11,
  duration_s: Math.round(60 + rnd() * 2400), direction: rnd() < 0.5 ? 'incoming' : 'outgoing',
  answered: rnd() < 0.85, missed: rnd() < 0.15, service: 'demo', address: `+1555010${10 + i}`,
  name: p.name, canonical_id: p.id }));

const birthdays = PEOPLE.slice(0, 10).map((p, i) => ({
  canonical_id: p.id, name: p.name, month: (i % 12) + 1, day: ((i * 7) % 27) + 1,
  year: 1990 + (i % 8), year_known: i % 3 !== 0, source: 'demo' }));

const links = [];
for (const p of PEOPLE) for (const q of PEOPLE) {
  if (p.id < q.id && rnd() < 0.28)
    links.push({ canonical_id: p.id, link_type: 'shared_group', related_canonical_id: q.id,
      related_label: q.name, evidence: 'co-member of a group thread', weight: 1 + Math.floor(rnd() * 4) });
}

// Rebuild from scratch: DuckDB will not re-create tables into an existing file.
fs.mkdirSync(path.dirname(OUT), { recursive: true });
for (const f of [OUT, `${OUT}.wal`]) if (fs.existsSync(f)) fs.rmSync(f);

const inst = await DuckDBInstance.create(OUT);
const c = await inst.connect();
const run = (sql) => c.run(sql);

await run(`CREATE TABLE identities (canonical_id VARCHAR, display_name VARCHAR, aliases VARCHAR[], sources VARCHAR[])`);
await run(`CREATE TABLE messages (id VARCHAR, ts BIGINT, ts_iso VARCHAR, source VARCHAR, thread_id VARCHAR, from_me BOOLEAN, sender_name VARCHAR, body VARCHAR, body_lower VARCHAR, meaningful BOOLEAN, attachment_type VARCHAR)`);
await run(`CREATE TABLE thread_identity (thread_id VARCHAR, canonical_id VARCHAR)`);
await run(`CREATE TABLE threads (thread_id VARCHAR, source VARCHAR, is_group BOOLEAN, participants VARCHAR[])`);
await run(`CREATE TABLE group_membership (thread_id VARCHAR, participant_name VARCHAR, canonical_id VARCHAR)`);
await run(`CREATE TABLE mentions (mentioned_canonical_id VARCHAR, mentioned_form VARCHAR, thread_id VARCHAR, message_id VARCHAR, ts BIGINT, from_me BOOLEAN)`);
await run(`CREATE TABLE photos (id VARCHAR, ts BIGINT, ts_iso VARCHAR, source VARCHAR, source_ref VARCHAR, message_id VARCHAR, asset_path VARCHAR, width INTEGER, height INTEGER, hash_sha256 VARCHAR, has_named_face BOOLEAN)`);
await run(`CREATE TABLE photo_faces (photo_id VARCHAR, canonical_id VARCHAR, face_cluster VARCHAR)`);
await run(`CREATE TABLE photo_face_dets (det_id VARCHAR, photo_id VARCHAR, bbox VARCHAR, det_score DOUBLE, cluster_id INTEGER)`);
await run(`CREATE TABLE face_clusters (cluster_id INTEGER, n_faces INTEGER, canonical_id VARCHAR, label VARCHAR, exemplar_photo_ids VARCHAR[])`);
await run(`CREATE TABLE places (photo_id VARCHAR, lat DOUBLE, lng DOUBLE, place_name VARCHAR, city VARCHAR, region VARCHAR, country VARCHAR)`);
await run(`CREATE TABLE reverse_geocode_cache (lat_round DOUBLE, lng_round DOUBLE, place_name VARCHAR, city VARCHAR, region VARCHAR, country VARCHAR)`);
await run(`CREATE TABLE events (event_id VARCHAR, start_ts BIGINT, end_ts BIGINT, place_name VARCHAR, participants VARCHAR[], n_photos INTEGER, n_messages INTEGER, summary VARCHAR, source VARCHAR, lat DOUBLE, lng DOUBLE)`);
await run(`CREATE TABLE event_photos (event_id VARCHAR, photo_id VARCHAR)`);
await run(`CREATE TABLE event_messages (event_id VARCHAR, message_id VARCHAR)`);
await run(`CREATE TABLE calls (call_id VARCHAR, ts BIGINT, duration_s DOUBLE, direction VARCHAR, answered BOOLEAN, missed BOOLEAN, service VARCHAR, address VARCHAR, name VARCHAR, canonical_id VARCHAR)`);
await run(`CREATE TABLE birthdays (canonical_id VARCHAR, name VARCHAR, month INTEGER, day INTEGER, year INTEGER, year_known BOOLEAN, source VARCHAR)`);
await run(`CREATE TABLE links (canonical_id VARCHAR, link_type VARCHAR, related_canonical_id VARCHAR, related_label VARCHAR, evidence VARCHAR, weight INTEGER)`);
await run(`CREATE TABLE fb_events (event_key VARCHAR, fbid VARCHAR, name VARCHAR, start_ts BIGINT, end_ts BIGINT, place_name VARCHAR, lat DOUBLE, lng DOUBLE, address VARCHAR, description VARCHAR, response VARCHAR, response_time BIGINT)`);
await run(`CREATE TABLE fb_event_topics (topic VARCHAR, n INTEGER, sample_events VARCHAR[])`);
await run(`CREATE TABLE email_meta (message_id VARCHAR, x_gm_thrid VARCHAR, labels VARCHAR[], category VARCHAR, in_reply_to VARCHAR, kind VARCHAR)`);
await run(`CREATE TABLE email_correspondents (addr VARCHAR, display_name VARCHAR, domain VARCHAR, kind VARCHAR, n_messages INTEGER, first_ts BIGINT, last_ts BIGINT, list_unsubscribe BOOLEAN, top_labels VARCHAR[])`);
await run(`CREATE TABLE yt_topics (kind VARCHAR, topic VARCHAR, count INTEGER, weight DOUBLE)`);

await run(`INSERT INTO identities VALUES ${[{ id: SELF_ID, name: SELF, sources: ['imessage'] }, ...PEOPLE.map((p) => ({ id: p.id, name: p.name, sources: p.sources }))]
  .map((p) => `(${esc(p.id)},${esc(p.name)},${arr([p.name])},${arr(p.sources)})`).join(',')}`);

const chunk = async (rows, sql) => { for (let i = 0; i < rows.length; i += 500) await run(sql(rows.slice(i, i + 500))); };
await chunk(messages, (b) => `INSERT INTO messages VALUES ${b.map((m) => `(${esc(m.id)},${m.ts},${esc(iso(m.ts))},${esc(m.source)},${esc(m.thread_id)},${m.from_me},${esc(m.sender_name)},${esc(m.body)},${esc(m.body.toLowerCase())},true,NULL)`).join(',')}`);
await run(`INSERT INTO thread_identity VALUES ${threadIdentity.map((r) => `(${esc(r.thread_id)},${esc(r.canonical_id)})`).join(',')}`);
await run(`INSERT INTO threads VALUES ${threads.map((r) => `(${esc(r.thread_id)},${esc(r.source)},${r.is_group},${arr(r.participants)})`).join(',')}`);
if (groupMembership.length) await run(`INSERT INTO group_membership VALUES ${groupMembership.map((r) => `(${esc(r.thread_id)},${esc(r.participant_name)},${esc(r.canonical_id)})`).join(',')}`);
if (mentions.length) await run(`INSERT INTO mentions VALUES ${mentions.map((r) => `(${esc(r.mentioned_canonical_id)},${esc(r.mentioned_form)},${esc(r.thread_id)},${esc(r.message_id)},${r.ts},${r.from_me})`).join(',')}`);
await run(`INSERT INTO photos VALUES ${photos.map((r) => `(${esc(r.id)},${r.ts},${esc(iso(r.ts))},${esc(r.source)},NULL,NULL,${esc(r.asset_path)},${r.width},${r.height},NULL,true)`).join(',')}`);
await run(`INSERT INTO photo_faces VALUES ${photoFaces.map((r) => `(${esc(r.photo_id)},${esc(r.canonical_id)},${esc(r.face_cluster)})`).join(',')}`);
await run(`INSERT INTO face_clusters VALUES ${faceClusters.map((r) => `(${r.cluster_id},${r.n_faces},${esc(r.canonical_id)},${esc(r.label)},${arr([])})`).join(',')}`);
await run(`INSERT INTO places VALUES ${places.map((r) => `(${esc(r.photo_id)},${r.lat},${r.lng},${esc(r.city)},${esc(r.city)},NULL,${esc(r.country)})`).join(',')}`);
await run(`INSERT INTO events VALUES ${events.map((r) => `(${esc(r.event_id)},${r.start_ts},${r.end_ts},${esc(r.place_name)},${arr(r.participants)},${r.n_photos},${r.n_messages},${esc(r.summary)},${esc(r.source)},${r.lat},${r.lng})`).join(',')}`);
await run(`INSERT INTO event_photos VALUES ${eventPhotos.map((r) => `(${esc(r.event_id)},${esc(r.photo_id)})`).join(',')}`);
await run(`INSERT INTO calls VALUES ${calls.map((r) => `(${esc(r.call_id)},${r.ts},${r.duration_s},${esc(r.direction)},${r.answered},${r.missed},${esc(r.service)},${esc(r.address)},${esc(r.name)},${esc(r.canonical_id)})`).join(',')}`);
await run(`INSERT INTO birthdays VALUES ${birthdays.map((r) => `(${esc(r.canonical_id)},${esc(r.name)},${r.month},${r.day},${r.year},${r.year_known},${esc(r.source)})`).join(',')}`);
if (links.length) await run(`INSERT INTO links VALUES ${links.map((r) => `(${esc(r.canonical_id)},${esc(r.link_type)},${esc(r.related_canonical_id)},${esc(r.related_label)},${esc(r.evidence)},${r.weight})`).join(',')}`);
await run(`INSERT INTO yt_topics VALUES ${['music', 'cooking', 'talks', 'repair', 'language'].map((t, i) => `('interest',${esc(t)},${20 - i * 3},${(1 - i * 0.15).toFixed(2)})`).join(',')}`);

c.closeSync(); inst.closeSync();
const kb = Math.round(fs.statSync(OUT).size / 1024);
console.log(`wrote ${path.relative(ROOT, OUT)} — ${messages.length} messages, ${PEOPLE.length + 1} identities, ${photos.length} photos, ${events.length} events (${kb} KB)`);
